trigger:
  branches:
    include:
    - release
   
variables:
- group: Databricks-stg-environment
- group: Databricks-prod-environment

stages:
{%{ if(params.test) { }%}
- stage: deploy_to_staging
  displayName: 'Deploy to staging'
  jobs:
  - template: ./template/deploy-notebook-job.yml
    parameters:
      environmentName: 'STG'
      databricksDomain: '$(databricksDomain_stg)'
      databricksToken: '$(databricksToken_stg)'
      databricksNotebookPath: '/Shared/notebook-tests/dbxbuild_$(Build.BuildId)/'


- stage: test_at_stg
  displayName: 'Test at staging'
  jobs:
  - template: ./template/test_notebook_job.yml
    parameters:
      environmentName: 'STG'
      databricksDomain: '$(databricksDomain_stg)'
      databricksToken: '$(databricksToken_stg)'
      databricksClusterId: '$(databricksClusterId_stg)'
      databricksNotebookPath: '/Shared/notebook-tests/dbxbuild_$(Build.BuildId)/'

{%{ } }%}

- stage: deploy_to_prod
  displayName: 'Deploy to production'
  condition: |
    and(
      startsWith(variables['Build.SourceBranch'], 'refs/heads/{%{=params.release_branch}%}')
{%{ if(params.test) { }%}      
      ,succeeded('test_at_stg')
{%{ } }%}
    )
  jobs:
  - template: ./template/deploy_notebook_job.yml
    parameters:
      environmentName: 'PROD'
      databricksDomain: '$(databricksDomain_prod)'
      databricksToken: '$(databricksToken_prod)'
      databricksNotebookPath: '/Shared/notebooks-release/'