trigger:
  branches:
    include:
    - dev
    - stg
    - prod

  paths:
    include:
    - src
    - tests

pool:
  vmImage: 'ubuntu-latest'


stages:
- stage: lint_checks_stage
  displayName: 'Lint checks'
  jobs:
  - job: lint_checks_job
    displayName: 'Lint checks'
    
    steps:
    - script: |
        python -m pip install --upgrade pip
        python -m pip install flake8
        python -m flake8 --ignore E501
      displayName: 'Lint checks'


- stage: model_training_test_stage
  displayName: 'Model Training Test'
  dependsOn: lint_checks_stage
  condition: succeeded('lint_checks_stage')
  jobs:
  - job: model_training_test_job
    displayName: 'Model Training Test'
    steps:
    - script: |
        python -m pip install --upgrade pip
        pip install -r 'requirements.txt' --use-deprecated=legacy-resolver
        pip install torch==1.6.0 torchvision==0.7.0 pandas==1.3.2 scikit-learn==0.24.2
      displayName: 'Install dependencies'
      workingDirectory: "$(System.DefaultWorkingDirectory)/"

    - script: |
        # Trigger a slim mlflow model training with 'local' backend, then check whether model file has been generated or not
        python -m pytest tests/test_model_training.py --junitxml=test_mlops.xml --disable-pytest-warnings
      workingDirectory: '$(System.DefaultWorkingDirectory)/'
      displayName: "Model Training Test"
      env:
        TRAINING_PLATFORM: 'local'

    - task: PublishTestResults@2
      displayName: Publish UT results
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/test*.xml'
        failTaskOnFailedTests: true
        testRunTitle: 'Publish UT results'
